<?php
include 'handleAssetMessages.php'
?>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Send Chromebook Out for Repair | SnipeTools</title>
	<link rel = "stylesheet" href = "style.css">
</head>
<body>
	<?php echo $audioMessage; ?>
	<div id = "page">
	<h1>Send Chromebook Out For Repair</h1>

	<form action="../api_requests/outForRepairAPI.php" method="GET" autocomplete="on">
		<label for="serial">Scan Serial #</label>
		<input type="hidden" name="source" value="outForRepair">
		<input type="text" id="serial" name="serial" autofocus required autocomplete="off">
		<button type="submit">Submit</button> <!-- Submit button is here for convenience if manually typing in serial, pressing enter works fine-->
		<br>
		<input type="checkbox" id="GAdmin" name="GAdmin" value="on" <?php echo (isset($_GET['GoogleRequestStatus']) ? 'checked' : ''); ?>>
		<label> Make sure this asset is provisioned in Google Admin (optional)</label>
		<br>
	</form>

	<h2><?php echo $assetMessage1; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetMessage2; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetLink; ?></h3> <!-- Generated by handleAssetMessages.php-->
	<a href="../index.php" class="menu">Return Home</a>
	
	</div>
</body>
</html>