<?php
include 'handleAssetMessages.php'
?>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Bring Working Chromebooks to Schools | SnipeTools</title>
	<link rel = "stylesheet" href = "style.css">
</head>
<body>
	<?php echo $audioMessage; ?>
	<div id = "page">
	<h1>Bring Working Chromebooks to Schools</h1>

	<form action="../api_requests/workingToSchoolsAPI.php" method="GET" autocomplete="on">
		<label for="serial">Scan Serial #</label>
		<input type="hidden" name="source" value="workingToSchools">
		<input type="text" id="serial" name="serial" autofocus required autocomplete="off">
		<button type="submit">Submit</button> <!-- Submit button is here for convenience if manually typing in serial, pressing enter works fine-->
		<br>
		<div id = "location">			
				<label>What School is this Chromebook going to? </label>
				<select name="location" id="location" required>
					<option value="5" <?php echo ((isset($_GET['location']) and $_GET['location'] == "5")?("selected"):(""));?>>Dayton</option>
					<option value="7" <?php echo ((isset($_GET['location']) and $_GET['location'] == "7")?("selected"):(""));?>>Elderton Elementary</option>
					<option value="9" <?php echo ((isset($_GET['location']) and $_GET['location'] == "9")?("selected"):(""));?>>Shannock Valley</option>
					<option value="8" <?php echo ((isset($_GET['location']) and $_GET['location'] == "8")?("selected"):(""));?>>Lenape Elementary</option>
					<option value="2" <?php echo ((isset($_GET['location']) and $_GET['location'] == "2")?("selected"):(""));?>>West Hills Primary</option>
					<option value="4" <?php echo ((isset($_GET['location']) and $_GET['location'] == "4")?("selected"):(""));?>>West Hills Intermediate</option>
					<option value="3" <?php echo ((isset($_GET['location']) and $_GET['location'] == "3")?("selected"):(""));?>>Armstrong High School</option>
					<option value="6" <?php echo ((isset($_GET['location']) and $_GET['location'] == "6")?("selected"):(""));?>>West Shamokin High School</option>
				</select>
				<br>
		<input type="checkbox" id="GAdmin" name="GAdmin" value="on" <?php echo (isset($_GET['GoogleRequestStatus']) ? 'checked' : ''); ?>>
		<label> Make sure this asset is provisioned in Google Admin (optional)</label>
		<br>
	</form>

	<h2><?php echo $assetMessage1; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetMessage2; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetLink; ?></h3> <!-- Generated by handleAssetMessages.php-->
	<a href="../index.php" class="menu">Return Home</a>
	
	</div>
</body>
</html>